version: '3.8'
services:
    app:
        build: .
        container_name: nest-app
        env_file:
            - .env
        ports:
            - '${APP_PORT}:3000'
        depends_on:
            - database
        restart: on-failure

    database:
        image: postgres:16
        container_name: postgres-db
        ports:
            - '${POSTGRES_PORT}:5432'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: on-failure

volumes:
    pgdata:
