services:
    app:
        volumes:
            - .:/app # Снести на проде
            - /app/node_modules # Снести на проде
        command: /bin/bash -c "wait-for-it database:5432 -- npm run start:dev" # Снести на проде
        build:
            context: .
            dockerfile: docker/dockerfile.dev # Поменять на .prod
        container_name: nest-app
        env_file:
            - .env
        ports:
            - '${APP_PORT}:3000'
        depends_on:
            - database
        restart: on-failure

    database:
        image: postgres:16
        container_name: postgres-db
        ports:
            - '${POSTGRES_PORT}:5432'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: on-failure

volumes:
    pgdata:
