# 1. Используем официальный образ Node.js
FROM node:22.9.0

# 2. Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# 3. Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# 4. Копируем только Prisma (если нужно)
COPY prisma ./prisma

# 5. Открываем порт
EXPOSE 3000

# 6. Устанавливаем зависимость для ожидания загрузки БД
RUN apt-get update && apt-get install -y wait-for-it

# 7. Запускаем в dev-режиме (например, с nodemon)
CMD ["npm", "run", "start:dev"]
